// ============ EXERCISES ============
// v = YouTube video id (embedded under the exercise), m = muscle, c = technique cues, s = spine note (osteochondrosis)
const EX = {
  bench_press:        { n: 'Bench Press', m: 'Chest', v: 'gMgvBspQ9lk', c: ['Shoulder blades back and down, chest up', 'Bar to the lower chest, elbows ~45°', 'Feet planted firmly'], s: 'Don’t over-arch your lower back' },
  incline_db_press:   { n: 'Incline Dumbbell Press', m: 'Chest (upper)', v: '5CECBjd7HLQ', c: ['Bench at 30°', 'Lower deep and controlled (2-3 s)', 'Don’t clash the dumbbells at the top'] },
  machine_chest_press:{ n: 'Machine Chest Press', m: 'Chest', v: '0Wa9CfRXUkA', c: ['Handles at mid-chest height', 'Full stretch at the bottom', 'Safe to take the last set to failure'] },
  machine_incline_press:{ n: 'Incline Machine Press', m: 'Chest (upper)', v: 'TrTSvn5-MTk', c: ['Back pressed into the pad', 'Slow eccentric', 'Don’t lock out the elbows at the top'] },
  db_flat_press:      { n: 'Dumbbell Flat Press', m: 'Chest', v: 'VmB1G1K7v94', c: ['Dumbbells down to the sides of the chest', 'Shoulder blades locked in', 'Press up in a slight arc'] },
  pec_deck:           { n: 'Pec Deck / Cable Fly', m: 'Chest', v: 'O-OBCfyh9Fw', c: ['Elbows slightly bent and fixed', 'Maximum stretch at the back', 'Squeeze for 1 second'] },
  cable_fly_low_high: { n: 'Low-to-High Cable Fly', m: 'Chest (upper)', v: 'e_8HLu59-to', c: ['Pulleys set low', 'Hands up and in, to chin height', 'Don’t shrug your shoulders'] },
  incline_barbell_press:{ n: 'Incline Barbell Press', m: 'Chest (upper)', v: 'lJ2o89kcnxY', c: ['Bench at 30°', 'Bar just below the collarbone', 'Controlled descent'] },
  dips:               { n: 'Dips', m: 'Chest / Triceps', v: '4LA1kF7yCGo', c: ['Lean forward slightly = more chest', 'Don’t go down into shoulder pain', 'Use Assisted Dips if needed'], s: 'If your back or shoulder can’t take it — skip' },
  pushup:             { n: 'Push-ups', m: 'Chest', v: 'mm6_WcoCVTA', c: ['Body in one straight line', 'Chest almost to the floor', 'To failure — without losing form'] },

  db_lateral_raise:   { n: 'Dumbbell Lateral Raise', m: 'Side delts', v: 'OuG1smZTsQQ', c: ['Elbow leads, higher than the hand', 'Up to shoulder height, not higher', 'No swinging'] },
  cable_lateral_raise:{ n: 'Cable Lateral Raise', m: 'Side delts', v: 'lq7eLC30b9w', c: ['Pulley low, cable behind the body', 'Constant tension, even at the bottom', 'Slow lowering'] },
  arnold_press:       { n: 'Arnold Press', m: 'Shoulders', v: '6Z15_WdXmVw', c: ['Start with palms facing you', 'Rotate as you press', 'Sit with back support'], s: 'Always use a bench with back support — less load on the spine' },
  shoulder_press:     { n: 'Seated DB Shoulder Press', m: 'Shoulders', v: 'HzIiNhHhhtA', c: ['Backrest ~80°', 'Dumbbells down to ear level', 'Lower back against the pad'], s: 'No standing barbell press — only with back support' },
  machine_shoulder_press:{ n: 'Machine Shoulder Press', m: 'Shoulders', v: 'WvLMauqrnK8', c: ['Seat so the handles are at chin height', 'Back against the pad', 'Slow lowering'] },
  cable_front_raise:  { n: 'Cable Front Raise', m: 'Front delts', v: 'yIoAcMD3jcE', c: ['Up to eye level', 'Body still', 'Slow lowering'] },
  upright_row:        { n: 'Upright Row (EZ bar)', m: 'Side delts / traps', v: 'um3VVzqunPU', c: ['Wide grip', 'Elbows to shoulder height, not higher', 'Stop if it hurts'], s: 'Shoulder impingement risk — be careful' },
  reverse_pec_deck:   { n: 'Reverse Pec Deck', m: 'Rear delts', v: '5YK4bgzXDp0', c: ['Arms out wide in an arc', 'Less shoulder blade, more rear delt', '1 second pause'] },
  face_pull:          { n: 'Face Pull', m: 'Rear delts / shoulder health', v: '-MODnZdnmAQ', c: ['Rope at face height', 'Rotate hands outward at the end', 'Light weight, clean form'] },

  rope_pushdown:      { n: 'Rope Pushdown', m: 'Triceps', v: '-xa-6cQaZKY', c: ['Elbows pinned to your sides', 'Spread the rope at the bottom', 'Only back up to 90°'] },
  single_arm_pushdown:{ n: 'Single-Arm Cable Pushdown', m: 'Triceps', v: 'Cp_bShvMY4c', c: ['One arm — full focus', 'Elbow still', 'Full extension at the bottom'] },
  oh_db_triceps:      { n: 'Overhead Triceps Extension', m: 'Triceps (long head)', v: 'gcRZqG8t44c', c: ['Sit with back support', 'Deep stretch behind the head', 'Don’t flare the elbows too much'], s: 'Sit, don’t stand — spares your lower back' },
  rope_oh_ext:        { n: 'Cable Overhead Extension', m: 'Triceps (long head)', v: 'kqidUIf1eJE', c: ['Back to the pulley, leaning forward slightly', 'Maximum stretch', 'Elbows beside the head'] },
  skull_crusher:      { n: 'Skull Crushers (EZ)', m: 'Triceps', v: 'l3rHYPtMUo8', c: ['Bar comes down behind the head', 'Elbows angled slightly back', 'Slow — protect your elbows'] },

  pullup:             { n: 'Pull-ups', m: 'Back (lats)', v: 'eGo4IYlbE5g', c: ['Full dead hang at the bottom', 'Chest toward the bar', 'No swinging — use Assisted if needed'], s: 'Hanging is good for the spine — finish with a 20-30 s dead hang' },
  weighted_pullup:    { n: 'Weighted Pull-ups', m: 'Back (lats)', v: 'HuuyDNGrCI8', c: ['Only once you have 10+ clean reps', 'Dip belt with weight', 'Full range of motion'] },
  lat_pulldown:       { n: 'Lat Pulldown (wide)', m: 'Back (lats)', v: 'YCKPD4BSD2E', c: ['Elbows down toward your pockets', 'Full stretch at the top', 'Don’t swing your torso'] },
  close_grip_pulldown:{ n: 'Close Grip Lat Pulldown', m: 'Back (lats)', v: 'GRHLNfmr_oI', c: ['V-handle', 'Pull to the upper chest', 'Let the shoulder blades rise fully at the top'] },
  chest_supported_row:{ n: 'Chest Supported Row', m: 'Back thickness', v: '0UBRfiO4zDs', c: ['Chest on the pad — spine protected', 'Drive the elbows back', 'Squeeze for 1 second'] },
  chest_supported_machine_row:{ n: 'Machine Chest-Supported Row', m: 'Back thickness', v: '_FrrYQxA6kc', c: ['Chest on the pad', 'Full stretch forward', 'Shoulder blades together'] },
  seated_cable_row:   { n: 'Seated Cable Row', m: 'Back thickness', v: 'UCXxvVItLoM', c: ['Torso almost still', 'Handle to the belly', 'Neutral lower back'], s: 'Don’t swing with your lower back — keep the spine neutral' },
  seated_row_machine: { n: 'Seated Row Machine', m: 'Back thickness', v: '_FrrYQxA6kc', c: ['Chest on the pad', 'Elbows back', 'Controlled'] },
  one_arm_db_row:     { n: 'One-Arm Dumbbell Row', m: 'Back', v: 'DMo3HJoawrU', c: ['Hand and knee on the bench — protects the back', 'Dumbbell toward the hip', 'Full stretch at the bottom'] },
  meadows_row:        { n: 'Meadows Row', m: 'Back', v: 'VpzKTWJy7Gs', c: ['Bar end in a landmine', 'Free hand braced on the knee', 'Elbow up and back'], s: 'Bent-over position — neutral lower back, moderate weight' },

  barbell_curl:       { n: 'Barbell / EZ Curl', m: 'Biceps', v: 'JnLFSFurrqQ', c: ['Elbows at your sides', 'Don’t swing the torso', 'Slow lowering, 2-3 s'] },
  incline_db_curl:    { n: 'Incline Dumbbell Curl', m: 'Biceps (long head)', v: 'aTYlqC_JacQ', c: ['Bench at 45-60°', 'Arms hanging straight down', 'Deep stretch'] },
  hammer_curl:        { n: 'Hammer Curl', m: 'Brachialis / forearms', v: 'XOEL4MgekYE', c: ['Neutral grip', 'Elbow still', 'Alternating or together'] },
  cable_curl:         { n: 'Cable Curl', m: 'Biceps', v: 'opFVuRi_3b8', c: ['Constant tension', 'Hard squeeze at the top', 'Pump finisher'] },
  preacher_curl:      { n: 'Preacher Curl', m: 'Biceps', v: 'sxA__DoLsgo', c: ['Armpit tight to the pad', 'Extend almost fully at the bottom', 'Don’t drop at the bottom'] },
  concentration_curl: { n: 'Concentration Curl', m: 'Biceps (peak)', v: 'Jvj2wV0vOYU', c: ['Elbow against the inner thigh', 'Wrist turned slightly out at the top', 'Slow'] },
  cable_high_curl:    { n: 'Cable High / Bayesian Curl', m: 'Biceps (peak)', v: 'w3sXATQzGvc', c: ['Pulley behind, arm behind the body', 'Maximum stretch', 'Squeeze at the peak'] },

  hack_squat:         { n: 'Hack Squat', m: 'Quads', v: 'rYgNArpwE7E', c: ['Whole back on the pad', 'As deep as you can without your lower back rounding', 'Knees track over the toes'], s: 'At the bottom your lower back must not lift off the pad' },
  smith_front_squat:  { n: 'Front Squat (Smith)', m: 'Quads', v: 'uIXkPdgaTss', c: ['Elbows high', 'Torso upright', 'Moderate weight'], s: 'Vertical load on the spine — don’t overload' },
  leg_press:          { n: 'Leg Press', m: 'Quads / glutes', v: 'yZmx_Ac3880', c: ['Lower back and pelvis stay on the pad', 'Don’t lock the knees at the top', 'Depth = as far as the pelvis stays stable'], s: 'Main risk: the pelvis tucking under at the bottom' },
  bulgarian_split_squat:{ n: 'Bulgarian Split Squat', m: 'Quads / glutes', v: 'jNihW0WDIL4', c: ['Rear foot on the bench', 'Torso slightly forward = more glutes', 'Dumbbells in hand, not a bar on the back'] },
  walking_lunge:      { n: 'Walking Lunges', m: 'Quads / glutes', v: 'eFWCn5iEbTU', c: ['Long stride', 'Back knee almost to the floor', 'Torso upright'] },
  leg_extension:      { n: 'Leg Extension', m: 'Quads', v: 'm0FOpMEgero', c: ['Backrest so the knee lines up with the pivot', '1 second pause at the top', 'Slow lowering'] },
  lying_leg_curl:     { n: 'Lying Leg Curl', m: 'Hamstrings', v: 'n5WDXD_mpVY', c: ['Hips pressed into the pad', 'Full range of motion', 'Slow lowering'] },
  seated_leg_curl:    { n: 'Seated Leg Curl', m: 'Hamstrings', v: 'Orxowest56U', c: ['Lean forward slightly — more stretch', 'Thigh pad snug', 'Controlled'] },
  db_rdl:             { n: 'Romanian Deadlift (DB)', m: 'Hamstrings / glutes', v: 'cYKYGwcg0U8', c: ['Hips back, back straight', 'Only go as low as your back stays neutral', 'Dumbbells close to the legs'], s: 'Most careful here! Moderate weight, never a rounded back' },
  hip_thrust:         { n: 'Hip Thrust', m: 'Glutes', v: 'EF7jXP17DPE', c: ['Chin toward the chest', 'At the top ribs down — don’t arch the lower back', '1-2 s squeeze'], s: 'Avoid lower-back hyperextension' },
  standing_calf_raise:{ n: 'Standing Calf Raise', m: 'Calves', v: 'N3awlEyTY98', c: ['1-2 s stretch at the bottom', 'All the way up on your toes', 'No bouncing'] },
  leg_press_calf:     { n: 'Leg Press Calf Raise', m: 'Calves', v: 'KxEYX_cuesM', c: ['No load on the spine', 'Deep stretch', 'Pause at the bottom'] },

  hanging_leg_raise:  { n: 'Hanging Leg Raise', m: 'Abs', v: '7FwGZ8qY5OU', c: ['Curl the pelvis up', 'No swinging', 'Hanging decompresses the spine'] },
  hanging_knee_raise: { n: 'Hanging Knee Raise', m: 'Abs', v: 'RD_A-Z15ER4', c: ['Knees toward the chest', 'Curl the pelvis', 'Lower slowly'] },
  cable_crunch:       { n: 'Cable Crunch', m: 'Abs', v: '6GMKPQVERzw', c: ['Crunch with the abs, not the hips', 'Head still', 'Moderate weight'], s: 'Moderate range — you don’t want heavy spinal flexion' },
  plank:              { n: 'Plank', m: 'Core', v: 'pvIjsG5Svck', c: ['Body in one line', 'Glutes squeezed', 'Breathe normally'] },
  side_plank:         { n: 'Side Plank', m: 'Obliques', v: 'iNbH7_edNI8', c: ['Don’t let the hips drop', 'Elbow under the shoulder', 'Each side'] },
  ab_wheel:           { n: 'Ab Wheel Rollout', m: 'Abs', v: 'vncVOEtMhpk', c: ['Start from your knees', 'Don’t let the lower back sag', 'Short range at first'], s: 'Heavy load on the lower back — risky with osteochondrosis' },
  pallof_press:       { n: 'Pallof Press', m: 'Core (anti-rotation)', v: 'tvzoG7Ua05Y', c: ['Pulley to your side', 'Press out and back, torso doesn’t rotate', 'Each side'] },
  dead_bug:           { n: 'Dead Bug', m: 'Core', v: 'o4GKiEoYClI', c: ['Lower back pressed to the floor', 'Opposite arm and leg', 'Slow, with breathing'] },
  mcgill_curlup:      { n: 'McGill Curl-Up', m: 'Core (spine protection)', v: 'vLpHJ1Cxj6k', c: ['One knee bent', 'Hands under the lower back', 'Lift head/shoulders slightly, hold 8-10 s'] },
  bird_dog:           { n: 'Bird Dog', m: 'Core (spine protection)', v: 'S1QbyYZaXIg', c: ['On all fours', 'Extend opposite arm and leg', 'Hold 8-10 s'] },
};

// Friday videos the user picked themselves (kept as-is)
const USER_V = {
  close_grip_pulldown: '51ql2-2kLfA', seated_row_machine: 'qD1WZ5pSuvk', rear_delt_note: 'Gs4e8eVMj-Q',
  barbell_curl: 'ez3YoWf62Eg', preacher_curl: '0y4tdUNPdlE', concentration_curl: '1IHm45rCvV4', cable_high_curl: 'w3sXATQzGvc',
};

// entry: [exerciseId, sets, reps, note?, videoOverride?, nameOverride?]
const WARMUP = [
  ['mcgill_curlup', 1, '5×10s', 'Every day — the McGill Big 3 for spine protection'],
  ['side_plank', 1, '3×10s each side'],
  ['bird_dog', 1, '4×8s each side'],
];

const PROGRAMS = {
  pro: {
    name: 'PRO plan',
    sub: 'Evidence-based PPL ×2 · spine-friendly · 60-75 min',
    days: [
      { t: 'Push A', f: 'Chest focus', ex: [
        ['incline_db_press', 3, '6-10', 'RIR 1-2 · rest 2-3 min'],
        ['machine_chest_press', 3, '8-12', 'Last set RIR 0'],
        ['shoulder_press', 3, '8-12'],
        ['cable_lateral_raise', 4, '12-20', 'Last set to failure'],
        ['cable_fly_low_high', 3, '12-15'],
        ['rope_oh_ext', 3, '10-15'],
        ['rope_pushdown', 2, '12-15'],
      ]},
      { t: 'Pull A', f: 'Back width', ex: [
        ['lat_pulldown', 4, '8-12', 'Or pull-ups if you have 8+ clean reps'],
        ['chest_supported_row', 3, '8-12', 'Chest support = spine protected'],
        ['seated_cable_row', 3, '10-12'],
        ['reverse_pec_deck', 3, '12-20'],
        ['incline_db_curl', 3, '8-12'],
        ['hammer_curl', 3, '10-15'],
      ]},
      { t: 'Legs A', f: 'Quad focus', ex: [
        ['hack_squat', 4, '6-10', 'If your lower back complains → Leg Press'],
        ['db_rdl', 3, '8-10', 'Moderate weight, back always straight'],
        ['leg_extension', 3, '10-15'],
        ['seated_leg_curl', 3, '10-15'],
        ['standing_calf_raise', 4, '10-15', '2 s pause at the bottom'],
        ['cable_crunch', 3, '10-15'],
        ['pallof_press', 3, '10 each side'],
      ]},
      { t: 'Push B', f: 'Shoulder focus', ex: [
        ['db_flat_press', 3, '6-10'],
        ['machine_incline_press', 3, '8-12'],
        ['machine_shoulder_press', 3, '8-12'],
        ['db_lateral_raise', 4, '12-20', 'Last set as a drop set'],
        ['pec_deck', 2, '12-15'],
        ['skull_crusher', 3, '8-12'],
        ['single_arm_pushdown', 2, '12-15'],
      ]},
      { t: 'Pull B', f: 'Back thickness + biceps', ex: [
        ['pullup', 3, '6-10', 'Assisted or weighted — depending on your level'],
        ['close_grip_pulldown', 3, '10-12'],
        ['chest_supported_machine_row', 3, '8-12'],
        ['one_arm_db_row', 3, '10-12'],
        ['face_pull', 3, '15-20'],
        ['barbell_curl', 3, '8-10'],
        ['preacher_curl', 2, '10-12'],
      ]},
      { t: 'Legs B', f: 'Glutes + hamstrings', ex: [
        ['leg_press', 4, '10-15', 'Feet high on the platform'],
        ['bulgarian_split_squat', 3, '8-12 each leg'],
        ['lying_leg_curl', 4, '10-12'],
        ['hip_thrust', 3, '8-12'],
        ['leg_press_calf', 4, '12-20'],
        ['hanging_knee_raise', 3, '12-15'],
        ['dead_bug', 3, '8 each side'],
      ]},
      { t: 'Rest', f: 'Swim + sauna', rest: true, ex: [] },
    ],
  },
  mine: {
    name: 'My plan',
    sub: 'Original (written by AI) · with your videos',
    days: [
      { t: 'Push', f: 'Chest, shoulders, triceps', ex: [
        ['bench_press', 5, '6-8', 'Barbell or dumbbell'],
        ['incline_db_press', 4, '8-10'],
        ['machine_chest_press', 4, '10-12'],
        ['db_lateral_raise', 5, '12-15'],
        ['arnold_press', 4, '8-10'],
        ['cable_front_raise', 3, '12-15'],
        ['rope_pushdown', 4, '12-15'],
        ['oh_db_triceps', 3, '10-12'],
        ['dips', 3, 'max', 'If your back can take it'],
      ]},
      { t: 'Pull', f: 'Back, biceps', ex: [
        ['pullup', 5, 'max', 'Neutral or supinated grip'],
        ['lat_pulldown', 4, '8-10'],
        ['chest_supported_row', 5, '8-10', 'T-bar or machine'],
        ['one_arm_db_row', 4, '10'],
        ['face_pull', 4, '12-15'],
        ['barbell_curl', 4, '8-10'],
        ['incline_db_curl', 4, '10-12'],
        ['hammer_curl', 4, '12'],
        ['cable_curl', 3, '15', 'pump finish'],
      ]},
      { t: 'Legs', f: 'Legs + core', ex: [
        ['hack_squat', 5, '8-10'],
        ['bulgarian_split_squat', 4, '10-12 each leg'],
        ['leg_press', 4, '12'],
        ['lying_leg_curl', 4, '12'],
        ['db_rdl', 4, '8-10', 'Dumbbell or trap bar, not too heavy'],
        ['standing_calf_raise', 5, '15-20'],
        ['hanging_leg_raise', 4, '12-15'],
        ['cable_crunch', 4, '15'],
        ['plank', 3, '30-60s'],
      ]},
      { t: 'Push', f: 'Chest, shoulders, triceps', ex: [
        ['incline_barbell_press', 5, '6-8'],
        ['db_flat_press', 4, '8-10'],
        ['pec_deck', 4, '12-15'],
        ['shoulder_press', 4, '8-10'],
        ['db_lateral_raise', 5, '15', 'drop set'],
        ['upright_row', 4, '10-12'],
        ['skull_crusher', 4, '8-10'],
        ['rope_oh_ext', 3, '12-15'],
        ['pushup', 1, 'to failure', 'finisher'],
      ]},
      { t: 'Pull', f: 'Back, biceps', ex: [
        ['weighted_pullup', 5, 'max'],
        ['close_grip_pulldown', 4, '10', '45 kg', USER_V.close_grip_pulldown],
        ['seated_row_machine', 4, '8-10', '35 kg', USER_V.seated_row_machine],
        ['meadows_row', 4, '10 each side'],
        ['reverse_pec_deck', 4, '12-15', '15 kg · your notes said "Meadows Row (machine/dumbbell)", but your video shows a Rear Delt Machine Fly', USER_V.rear_delt_note, 'Rear Delt Machine Fly'],
        ['barbell_curl', 4, '6-8', '17 kg', USER_V.barbell_curl],
        ['preacher_curl', 4, '10-12', '', USER_V.preacher_curl],
        ['concentration_curl', 3, '12', '', USER_V.concentration_curl],
        ['cable_high_curl', 3, '15', 'for peak', USER_V.cable_high_curl],
      ]},
      { t: 'Legs', f: 'Legs + core', ex: [
        ['smith_front_squat', 5, '6-8'],
        ['walking_lunge', 4, '20 steps'],
        ['leg_extension', 4, '12-15'],
        ['db_rdl', 4, '8-10', 'Dumbbells'],
        ['hip_thrust', 4, '12', 'Glute bridge / hip thrust'],
        ['standing_calf_raise', 5, '15-20'],
        ['ab_wheel', 4, '12-15'],
        ['side_plank', 3, '40-60s each side'],
        ['hanging_knee_raise', 4, '15'],
      ]},
      { t: 'Rest', f: 'Swim, sauna, jacuzzi', rest: true, ex: [] },
    ],
  },
};

const PRO_WHY = [
  ['⏱️', '90-120 min → 60-75 min', 'Your old plan has ~36-40 sets per session. Research (Schoenfeld 2017; Israetel, RP) shows that beyond ~6-10 hard sets per muscle per session growth barely increases while fatigue keeps rising. Fewer but harder sets = more muscle.'],
  ['🦴', 'Osteochondrosis', 'I removed or replaced the moves that load the spine the most: Smith Front Squat → Hack/Leg Press, Ab Wheel → Pallof/Dead Bug (Stuart McGill’s recommendation), Upright Row → Lateral Raise. Every row is chest-supported.'],
  ['🔥', 'McGill Big 3 every day', 'Curl-up, Side Plank, Bird Dog — the protocol of spine biomechanics professor Stuart McGill. ~6 min before training. Builds a strong core without flexing the spine.'],
  ['📈', 'Double progression', 'Once you hit the top of the rep range in every set (e.g. 3×12 in an 8-12 range) → add +2.5 kg next time. The app tells you when.'],
  ['🎯', 'RIR (Reps In Reserve)', 'RIR 2 = at the end of the set you could have done 2 more reps. Main lifts at RIR 1-2, isolation and machines at RIR 0-1.'],
  ['🔄', 'Deload every 6th week', 'Sets are halved, weight stays the same. Joints and nervous system recover — you come back stronger for the next cycle. The app counts the weeks automatically.'],
  ['📊', '~12-20 sets per muscle per week', 'Each muscle twice a week — the optimal frequency for hypertrophy (Schoenfeld et al. 2016 meta-analysis).'],
];

// ============ MEALS ============
// i: [grams|null, name] ; k/p/c/f per base portion
const MEALS = {
  oat_pancakes: { n: 'Protein oat pancakes', en: 'Oatmeal pancakes', img: 'm53331.jpg', type: 'b', k: 645, p: 40, c: 88, f: 15, t: 15,
    i: [[80, 'rolled oats'], [100, 'eggs (2)'], [120, 'banana'], [150, 'skyr / Greek yogurt'], [null, 'cinnamon']],
    s: ['Blend the oats, eggs and banana', 'Non-stick pan on low heat, 2 min per side', 'Top with yogurt and berries'] },
  omelette: { n: 'Omelette + wholegrain bread', en: 'French omelette', img: 'm52915.jpg', type: 'b', k: 605, p: 34, c: 42, f: 31, t: 10,
    i: [[150, 'eggs (3)'], [30, 'sulguni / feta'], [100, 'spinach, tomato'], [80, 'wholegrain bread'], [50, 'avocado']],
    s: ['Whisk the eggs with salt', 'Cook on low heat, cheese and greens in the middle', 'Fold and serve with bread and avocado'] },
  overnight_oats: { n: 'Protein overnight oats', en: 'Protein overnight oats', img: 'w_oats.jpg', type: 'b', k: 600, p: 42, c: 77, f: 14, t: 5,
    i: [[70, 'oats'], [30, 'whey protein'], [200, 'milk 1.5%'], [100, 'berries'], [15, 'chia seeds']],
    s: ['Mix everything in a jar', 'Fridge overnight', 'Ready in the morning — perfect when you’re in a hurry'] },
  buckwheat_eggs: { n: 'Buckwheat with eggs', en: 'Buckwheat porridge', img: 'w_buckwheat.jpg', type: 'b', k: 550, p: 31, c: 68, f: 17, t: 20,
    i: [[90, 'buckwheat (dry)'], [150, 'eggs (3)'], [150, 'cucumber, tomato']],
    s: ['Rinse the buckwheat, simmer 1:2 in water for 15 min', 'Boil or pan-fry the eggs', 'Serve with salad'] },

  chicken_quinoa: { n: 'Chicken & quinoa Greek salad', en: 'Chicken quinoa Greek salad', img: 'm53011.jpg', type: 'm', k: 706, p: 61, c: 50, f: 29, t: 25,
    i: [[200, 'chicken breast'], [70, 'quinoa (dry)'], [150, 'cucumber, tomato, onion'], [30, 'olives'], [40, 'feta'], [10, 'olive oil']],
    s: ['Cook the quinoa for 15 min', 'Grill/pan-fry the chicken, 6-7 min per side', 'Mix everything, add lemon and oil'] },
  teriyaki_salmon: { n: 'Teriyaki salmon with rice', en: 'Honey teriyaki salmon', img: 'm52773.jpg', type: 'm', k: 785, p: 47, c: 90, f: 25, t: 25,
    i: [[180, 'salmon'], [90, 'basmati rice (dry)'], [150, 'broccoli'], [15, 'soy sauce + honey']],
    s: ['Marinate the salmon in the sauce for 10 min', 'Oven at 200°C for 12-14 min', 'Rice and steamed broccoli'] },
  baked_salmon: { n: 'Baked salmon with potatoes', en: 'Baked salmon, fennel & tomatoes', img: 'm52959.jpg', type: 'm', k: 700, p: 44, c: 61, f: 29, t: 35,
    i: [[180, 'salmon'], [300, 'potatoes'], [200, 'fennel, cherry tomatoes'], [5, 'olive oil']],
    s: ['Cut the potatoes, roast at 200°C for 15 min', 'Add the salmon and vegetables', 'Another 15 min'] },
  tandoori_chicken: { n: 'Tandoori chicken with rice', en: 'Tandoori chicken', img: 'm52806.jpg', type: 'm', k: 660, p: 59, c: 78, f: 11, t: 40,
    i: [[220, 'chicken thigh (skinless)'], [80, 'Greek yogurt (marinade)'], [90, 'basmati (dry)'], [150, 'salad'], [null, 'tandoori spices']],
    s: ['Marinate the chicken in yogurt and spices for 1 h+', 'Oven at 220°C for 25 min', 'Serve with rice and salad'] },
  chicken_skewers: { n: 'Chicken skewers with pita', en: 'Smoky chicken skewers', img: 'm53264.jpg', type: 'm', k: 612, p: 68, c: 47, f: 15, t: 30,
    i: [[220, 'chicken breast'], [200, 'peppers, onion'], [60, 'wholegrain pita'], [100, 'yogurt-garlic sauce'], [10, 'olive oil']],
    s: ['Cube the chicken, add paprika + garlic', 'Thread onto skewers with the vegetables', 'Grill for 10-12 min'] },
  beef_stirfry: { n: 'Beef stir-fry', en: 'Thai beef stir-fry', img: 'm53199.jpg', type: 'm', k: 710, p: 51, c: 80, f: 21, t: 20,
    i: [[200, 'lean beef'], [80, 'rice noodles (dry)'], [250, 'vegetables'], [10, 'oil'], [15, 'soy sauce']],
    s: ['Slice the beef thinly', 'Very hot pan, 2-3 min', 'Vegetables + noodles + sauce, 3 min'] },
  turkey_meatloaf: { n: 'Turkey meatloaf with potatoes', en: 'Turkey meatloaf', img: 'm52845.jpg', type: 'm', k: 776, p: 60, c: 75, f: 24, t: 60,
    i: [[220, 'ground turkey'], [30, 'oats'], [50, 'egg (1)'], [300, 'potatoes'], [150, 'salad']],
    s: ['Mix the turkey, oats, egg and onion', 'Bake in a tin at 180°C for 45 min', 'Make it for 3 days — meal prep'] },
  tuna_nicoise: { n: 'Tuna Niçoise', en: 'Tuna Niçoise', img: 'm52852.jpg', type: 'm', k: 664, p: 58, c: 55, f: 24, t: 20,
    i: [[150, 'tuna (in its own juice)'], [100, 'eggs (2)'], [250, 'potatoes'], [150, 'green beans'], [20, 'olives'], [10, 'olive oil']],
    s: ['Boil the potatoes and eggs', 'Green beans for 4 min', 'Plate everything, mustard-lemon dressing'] },
  chicken_couscous: { n: 'Chicken with couscous', en: 'Chicken couscous', img: 'm52850.jpg', type: 'm', k: 789, p: 65, c: 96, f: 16, t: 25,
    i: [[200, 'chicken breast'], [80, 'couscous (dry)'], [200, 'vegetables'], [80, 'cooked chickpeas'], [10, 'olive oil']],
    s: ['Cut and pan-fry the chicken', 'Add vegetables + chickpeas', 'Pour hot stock over the couscous, cover for 5 min'] },
  lentil_chili: { n: 'Lentil chili with squash', en: 'Smoky lentil chili', img: 'm52784.jpg', type: 'm', k: 645, p: 44, c: 98, f: 12, t: 45,
    i: [[100, 'lentils (dry)'], [200, 'squash'], [200, 'tomatoes'], [10, 'olive oil'], [150, 'Greek yogurt 0%']],
    s: ['Onion, garlic, smoked paprika', 'Lentils, squash, tomatoes, water', '35 min; top with yogurt'] },
  stuffed_peppers: { n: 'Quinoa & bean stuffed peppers', en: 'Stuffed peppers', img: 'm53067.jpg', type: 'm', k: 660, p: 32, c: 95, f: 15, t: 45,
    i: [[60, 'quinoa (dry)'], [150, 'black beans (cooked)'], [300, 'bell peppers (3)'], [40, 'cheese'], [100, 'salsa']],
    s: ['Cook the quinoa, mix with beans and salsa', 'Stuff the peppers, cheese on top', '190°C for 30 min · +200 g skyr for protein'] },
  jerk_chicken: { n: 'Jerk chicken with rice & beans', en: 'Jerk chicken with rice & peas', img: 'm52937.jpg', type: 'm', k: 722, p: 59, c: 86, f: 15, t: 40,
    i: [[220, 'chicken thigh'], [80, 'rice (dry)'], [100, 'red kidney beans'], [50, 'coconut milk (light)'], [null, 'jerk spices']],
    s: ['Marinate the chicken', 'Grill/oven for 25 min', 'Rice with beans and coconut milk'] },
  lobio: { n: 'Lobio with mchadi + chicken', en: 'Georgian lobio', img: 'w_lobio.jpg', type: 'm', k: 800, p: 64, c: 104, f: 13, t: 30,
    i: [[250, 'red beans (cooked)'], [15, 'walnuts'], [100, 'mchadi (cornbread)'], [150, 'boiled chicken breast'], [null, 'coriander, onion, pickled bladdernut']],
    s: ['Cook the beans, half-mash them', 'Onion, walnuts, herbs', 'Chicken for protein — Georgian + athletic'] },

  skyr_berries: { n: 'Skyr with berries', en: 'Skyr & berries', img: 'w_skyr.jpg', type: 's', k: 361, p: 30, c: 35, f: 10, t: 2,
    i: [[250, 'skyr / Greek yogurt'], [150, 'berries'], [10, 'honey'], [15, 'walnuts']], s: ['Mix and enjoy'] },
  protein_shake: { n: 'Post-workout shake', en: 'Protein shake', img: 'w_shake.jpg', type: 's', k: 538, p: 44, c: 71, f: 9, t: 3,
    i: [[35, 'whey protein'], [120, 'banana'], [300, 'milk 1.5%'], [40, 'oats'], [5, 'creatine (5 g)']], s: ['Everything in the blender', 'Within 0-2 h after training'] },
  cottage_cheese: { n: 'Cottage cheese with apple & almonds', en: 'Cottage cheese', img: 'w_cottage.jpg', type: 's', k: 435, p: 35, c: 38, f: 15, t: 2,
    i: [[250, 'cottage cheese 2-5%'], [180, 'apple'], [20, 'almonds']], s: ['Ideal before bed — casein feeds your muscles overnight'] },
};

// 7-day rotation: [breakfast, snack, lunch, post-workout, dinner]
const MEAL_DAYS = [
  ['oat_pancakes', 'skyr_berries', 'chicken_quinoa', 'protein_shake', 'teriyaki_salmon'],
  ['omelette', 'cottage_cheese', 'beef_stirfry', 'protein_shake', 'tandoori_chicken'],
  ['overnight_oats', 'skyr_berries', 'turkey_meatloaf', 'protein_shake', 'tuna_nicoise'],
  ['buckwheat_eggs', 'cottage_cheese', 'chicken_couscous', 'protein_shake', 'baked_salmon'],
  ['oat_pancakes', 'skyr_berries', 'turkey_meatloaf', 'protein_shake', 'jerk_chicken'],
  ['omelette', 'cottage_cheese', 'chicken_skewers', 'protein_shake', 'lentil_chili'],
  ['overnight_oats', 'skyr_berries', 'lobio', 'cottage_cheese', 'stuffed_peppers'],
];
const SLOT = ['Breakfast', 'Snack', 'Lunch', 'Post-workout', 'Dinner'];

const NUTRI_RULES = [
  ['🥩', 'Protein: 2.0 g/kg per day', 'ISSN (International Society of Sports Nutrition): 1.6–2.2 g/kg. Split over 4-5 meals, ~0.4 g/kg each (Schoenfeld & Aragon 2018).'],
  ['📈', 'Lean bulk: +10% calories', 'Target: +0.25–0.5% of body weight per week. A one-size-fits-all 3500-4000 kcal doesn’t work — the app tracks your weight and adjusts calories weekly so you gain muscle, not fat (Iraki et al. 2019).'],
  ['🫒', 'Fat: 0.8–1 g/kg', 'Don’t drop below 20% for testosterone and hormones. Salmon twice a week (omega-3).'],
  ['🍚', 'Carbs: the rest', 'Fuel for training. More before and after workouts.'],
  ['🥦', '30–40 g fiber + 5 servings of vegetables/fruit', 'Gut, immunity, lower inflammation.'],
  ['💧', 'Water: 35–40 ml/kg', '+0.5–1 L on training days.'],
  ['💊', 'Creatine monohydrate 3–5 g', 'The best-researched supplement (ISSN 2017). Every day, timing doesn’t matter.'],
  ['😴', 'Sleep 7–9 h', 'Muscle grows while you sleep. <6 h sleep sharply lowers protein synthesis and testosterone.'],
];

// ============ SWIM & SAUNA ============
const SWIM_PLAN = {
  t: 'Swim — spine and heart training', min: 30, m: 900,
  v: [['6_vXycbD2TM', 'Freestyle (crawl)'], ['MrFt6JHii8w', 'Backstroke']],
  sets: [
    ['200 m', 'easy freestyle — warm-up'],
    ['4×50 m', 'backstroke · 20 s rest — decompresses the spine, opens the shoulders'],
    ['6×50 m', 'freestyle at moderate pace · 30 s rest'],
    ['4×25 m', 'legs only, with a kickboard'],
    ['200 m', 'easy — cool-down'],
  ],
  rules: [
    'Don’t swim breaststroke with your head above water — it hyperextends the neck and lower back. If breaststroke, face in the water.',
    'On strength days swim after training or in the evening, easy. Nothing intense before a leg day.',
    '2-3 times a week for 20-40 min — heart, lungs, recovery without loading the spine.',
  ],
};
const SAUNA_PROTOCOL = {
  steps: [
    ['🧖', '2-3 rounds × 10-15 min', '80-90°C. Start with 8-10 min the first few times'],
    ['🚿', '2-5 min cool shower between rounds', 'Or the pool. Trains the heart and wakes you up'],
    ['💧', '0.5-1 L water + salt/electrolytes', 'Every 10 min of sauna costs ~0.3-0.5 L of sweat'],
    ['⏰', 'After training or on a rest day', 'Never before strength training — strength and endurance drop'],
    ['🚫', 'Not after alcohol or when you feel unwell', 'Get out immediately if you feel dizzy'],
  ],
  why: 'A 20-year Finnish study (Laukkanen et al., JAMA Internal Medicine 2015, 2,315 men): 4-7 sauna sessions a week — ~50% lower cardiovascular mortality than once a week. 2-3 times still brings meaningful benefit. Also: growth hormone, recovery, sleep, stress.',
};
