// Word decks, ordered roughly by usefulness. [foreign, georgian, hint]
// Portuguese = European Portuguese (pt-PT) spelling and vocabulary
const WORDS = {
  pt: [
    ['olá', 'გამარჯობა', 'hello'], ['obrigado / obrigada', 'მადლობა (კაცი / ქალი ამბობს)', 'thank you'], ['por favor', 'გთხოვ', 'please'], ['sim', 'კი', 'yes'], ['não', 'არა', 'no'],
    ['desculpe', 'უკაცრავად', 'sorry / excuse me'], ['bom dia', 'დილა მშვიდობისა', 'good morning'], ['boa tarde', 'დღე მშვიდობისა', 'good afternoon'], ['boa noite', 'საღამო / ღამე მშვიდობისა', 'good evening/night'], ['adeus', 'ნახვამდის', 'goodbye'],
    ['até logo', 'მოგვიანებით შევხვდეთ', 'see you later'], ['de nada', 'არაფრის', 'you are welcome'], ['com licença', 'ნებართვით', 'excuse me (pass)'], ['tudo bem?', 'როგორ ხარ? / ყველაფერი რიგზეა?', 'all good?'], ['eu', 'მე', 'I'],
    ['tu', 'შენ', 'you (informal)'], ['você', 'თქვენ / შენ (ზრდილობიანი)', 'you (polite)'], ['ele', 'ის (მამრ.)', 'he'], ['ela', 'ის (მდედრ.)', 'she'], ['nós', 'ჩვენ', 'we'],
    ['eles / elas', 'ისინი', 'they'], ['ser', 'ყოფნა (მუდმივი თვისება)', 'to be (permanent)'], ['estar', 'ყოფნა (დროებითი მდგომარეობა)', 'to be (temporary)'], ['ter', 'ქონა', 'to have'], ['fazer', 'კეთება', 'to do / make'],
    ['ir', 'წასვლა', 'to go'], ['vir', 'მოსვლა', 'to come'], ['ver', 'ნახვა', 'to see'], ['dar', 'მიცემა', 'to give'], ['dizer', 'თქმა', 'to say'],
    ['poder', 'შეძლება', 'can / to be able'], ['querer', 'ნდომა', 'to want'], ['saber', 'ცოდნა (ფაქტის)', 'to know (facts)'], ['conhecer', 'ცნობა (ადამიანის, ადგილის)', 'to know (people/places)'], ['falar', 'ლაპარაკი', 'to speak'],
    ['comer', 'ჭამა', 'to eat'], ['beber', 'დალევა', 'to drink'], ['dormir', 'ძილი', 'to sleep'], ['trabalhar', 'მუშაობა', 'to work'], ['viver', 'ცხოვრება', 'to live'],
    ['morar', 'ცხოვრება (სადმე)', 'to reside'], ['gostar de', 'მოწონება', 'to like'], ['precisar de', 'საჭიროება', 'to need'], ['pensar', 'ფიქრი', 'to think'], ['perceber', 'გაგება (pt-PT)', 'to understand'],
    ['comprar', 'ყიდვა', 'to buy'], ['pagar', 'გადახდა', 'to pay'], ['abrir', 'გახსნა', 'to open'], ['fechar', 'დახურვა', 'to close'], ['começar', 'დაწყება', 'to start'],
    ['acabar', 'დამთავრება', 'to finish'], ['esperar', 'ლოდინი / იმედი', 'to wait / hope'], ['ajudar', 'დახმარება', 'to help'], ['chegar', 'მისვლა / ჩამოსვლა', 'to arrive'], ['sair', 'გასვლა', 'to leave / go out'],
    ['entrar', 'შესვლა', 'to enter'], ['voltar', 'დაბრუნება', 'to return'], ['ficar', 'დარჩენა', 'to stay'], ['levar', 'წაღება', 'to take (away)'], ['trazer', 'მოტანა', 'to bring'],
    ['ler', 'კითხვა', 'to read'], ['escrever', 'წერა', 'to write'], ['ouvir', 'მოსმენა', 'to hear / listen'], ['perguntar', 'კითხვის დასმა', 'to ask'], ['responder', 'პასუხის გაცემა', 'to answer'],
    ['aprender', 'სწავლა', 'to learn'], ['ensinar', 'სწავლება', 'to teach'], ['andar', 'სიარული', 'to walk'], ['correr', 'სირბილი', 'to run'], ['nadar', 'ცურვა', 'to swim'],
    ['cozinhar', 'საჭმლის მომზადება', 'to cook'], ['lavar', 'რეცხვა', 'to wash'], ['limpar', 'დასუფთავება', 'to clean'], ['usar', 'გამოყენება', 'to use'], ['encontrar', 'პოვნა / შეხვედრა', 'to find / meet'],
    ['perder', 'დაკარგვა / წაგება', 'to lose'], ['ganhar', 'მოგება / გამომუშავება', 'to win / earn'], ['mudar', 'შეცვლა', 'to change'], ['acordar', 'გაღვიძება', 'to wake up'], ['lembrar-se', 'გახსენება', 'to remember'],
    ['esquecer', 'დავიწყება', 'to forget'], ['sentir', 'გრძნობა', 'to feel'], ['tomar', 'მიღება / დალევა (tomar café)', 'to take / have'], ['chamar-se', 'დარქმევა (Como te chamas?)', 'to be called'], ['dançar', 'ცეკვა', 'to dance'],
    ['casa', 'სახლი', 'house'], ['água', 'წყალი', 'water'], ['comida', 'საჭმელი', 'food'], ['pão', 'პური', 'bread'], ['café', 'ყავა', 'coffee'],
    ['chá', 'ჩაი', 'tea'], ['leite', 'რძე', 'milk'], ['carne', 'ხორცი', 'meat'], ['peixe', 'თევზი', 'fish'], ['frango', 'ქათამი', 'chicken'],
    ['ovo', 'კვერცხი', 'egg'], ['arroz', 'ბრინჯი', 'rice'], ['fruta', 'ხილი', 'fruit'], ['legumes', 'ბოსტნეული', 'vegetables'], ['queijo', 'ყველი', 'cheese'],
    ['sal', 'მარილი', 'salt'], ['açúcar', 'შაქარი', 'sugar'], ['pequeno-almoço', 'საუზმე (pt-PT)', 'breakfast'], ['almoço', 'სადილი', 'lunch'], ['jantar', 'ვახშამი', 'dinner'],
    ['a conta', 'ანგარიში (რესტორანში)', 'the bill'], ['mesa', 'მაგიდა', 'table'], ['cadeira', 'სკამი', 'chair'], ['porta', 'კარი', 'door'], ['janela', 'ფანჯარა', 'window'],
    ['quarto', 'ოთახი / საძინებელი', 'room / bedroom'], ['cozinha', 'სამზარეულო', 'kitchen'], ['casa de banho', 'აბაზანა / ტუალეტი (pt-PT)', 'bathroom'], ['cama', 'საწოლი', 'bed'], ['rua', 'ქუჩა', 'street'],
    ['cidade', 'ქალაქი', 'city'], ['país', 'ქვეყანა', 'country'], ['praia', 'პლაჟი', 'beach'], ['mar', 'ზღვა', 'sea'], ['rio', 'მდინარე', 'river'],
    ['sol', 'მზე', 'sun'], ['chuva', 'წვიმა', 'rain'], ['tempo', 'დრო / ამინდი', 'time / weather'], ['dia', 'დღე', 'day'], ['noite', 'ღამე', 'night'],
    ['manhã', 'დილა', 'morning'], ['tarde', 'ნაშუადღევი / გვიან', 'afternoon / late'], ['semana', 'კვირა (7 დღე)', 'week'], ['mês', 'თვე', 'month'], ['ano', 'წელი', 'year'],
    ['hoje', 'დღეს', 'today'], ['amanhã', 'ხვალ', 'tomorrow'], ['ontem', 'გუშინ', 'yesterday'], ['agora', 'ახლა', 'now'], ['depois', 'შემდეგ', 'after / later'],
    ['antes', 'მანამდე', 'before'], ['sempre', 'ყოველთვის', 'always'], ['nunca', 'არასდროს', 'never'], ['às vezes', 'ზოგჯერ', 'sometimes'], ['já', 'უკვე', 'already'],
    ['ainda', 'ჯერ კიდევ', 'still / yet'], ['cedo', 'ადრე', 'early'], ['homem', 'კაცი', 'man'], ['mulher', 'ქალი', 'woman'], ['criança', 'ბავშვი', 'child'],
    ['amigo / amiga', 'მეგობარი', 'friend'], ['família', 'ოჯახი', 'family'], ['pai', 'მამა', 'father'], ['mãe', 'დედა', 'mother'], ['irmão', 'ძმა', 'brother'],
    ['irmã', 'და', 'sister'], ['filho', 'ვაჟიშვილი', 'son'], ['filha', 'ქალიშვილი', 'daughter'], ['pessoa', 'ადამიანი', 'person'], ['as pessoas', 'ხალხი', 'people'],
    ['corpo', 'სხეული', 'body'], ['cabeça', 'თავი', 'head'], ['mão', 'ხელი (მტევანი)', 'hand'], ['braço', 'მკლავი', 'arm'], ['perna', 'ფეხი', 'leg'],
    ['costas', 'ზურგი', 'back'], ['coração', 'გული', 'heart'], ['olho', 'თვალი', 'eye'], ['dor', 'ტკივილი', 'pain'], ['médico', 'ექიმი', 'doctor'],
    ['farmácia', 'აფთიაქი', 'pharmacy'], ['ginásio', 'სპორტდარბაზი (pt-PT)', 'gym'], ['treino', 'ვარჯიში', 'workout'], ['músculo', 'კუნთი', 'muscle'], ['saúde', 'ჯანმრთელობა', 'health'],
    ['cansado', 'დაღლილი', 'tired'], ['forte', 'ძლიერი', 'strong'], ['bom / boa', 'კარგი', 'good'], ['mau / má', 'ცუდი', 'bad'], ['grande', 'დიდი', 'big'],
    ['pequeno', 'პატარა', 'small'], ['novo', 'ახალი / ახალგაზრდა', 'new / young'], ['velho', 'ძველი / მოხუცი', 'old'], ['bonito', 'ლამაზი', 'beautiful'], ['quente', 'ცხელი', 'hot'],
    ['frio', 'ცივი', 'cold'], ['caro', 'ძვირი', 'expensive'], ['barato', 'იაფი', 'cheap'], ['fácil', 'მარტივი', 'easy'], ['difícil', 'რთული', 'difficult'],
    ['rápido', 'სწრაფი', 'fast'], ['devagar', 'ნელა', 'slowly'], ['cheio', 'სავსე', 'full'], ['vazio', 'ცარიელი', 'empty'], ['aberto', 'ღია', 'open'],
    ['fechado', 'დაკეტილი', 'closed'], ['feliz', 'ბედნიერი', 'happy'], ['triste', 'სევდიანი', 'sad'], ['certo', 'სწორი', 'right / correct'], ['errado', 'არასწორი', 'wrong'],
    ['perto', 'ახლოს', 'near'], ['longe', 'შორს', 'far'], ['aqui', 'აქ', 'here'], ['ali', 'იქ', 'there'], ['o quê?', 'რა?', 'what?'],
    ['quem?', 'ვინ?', 'who?'], ['onde?', 'სად?', 'where?'], ['quando?', 'როდის?', 'when?'], ['porquê?', 'რატომ?', 'why?'], ['como?', 'როგორ?', 'how?'],
    ['quanto custa?', 'რა ღირს?', 'how much?'], ['qual?', 'რომელი?', 'which?'], ['um / uma', 'ერთი', 'one'], ['dois / duas', 'ორი', 'two'], ['três', 'სამი', 'three'],
    ['quatro', 'ოთხი', 'four'], ['cinco', 'ხუთი', 'five'], ['seis', 'ექვსი', 'six'], ['sete', 'შვიდი', 'seven'], ['oito', 'რვა', 'eight'],
    ['nove', 'ცხრა', 'nine'], ['dez', 'ათი', 'ten'], ['vinte', 'ოცი', 'twenty'], ['cem', 'ასი', 'hundred'], ['mil', 'ათასი', 'thousand'],
    ['branco', 'თეთრი', 'white'], ['preto', 'შავი', 'black'], ['vermelho', 'წითელი', 'red'], ['azul', 'ლურჯი', 'blue'], ['verde', 'მწვანე', 'green'],
    ['carro', 'მანქანა', 'car'], ['autocarro', 'ავტობუსი (pt-PT)', 'bus'], ['comboio', 'მატარებელი (pt-PT)', 'train'], ['avião', 'თვითმფრინავი', 'plane'], ['estação', 'სადგური', 'station'],
    ['bilhete', 'ბილეთი', 'ticket'], ['loja', 'მაღაზია', 'shop'], ['mercado', 'ბაზარი', 'market'], ['dinheiro', 'ფული', 'money'], ['trabalho', 'სამუშაო', 'work / job'],
    ['livro', 'წიგნი', 'book'], ['telemóvel', 'მობილური ტელეფონი (pt-PT)', 'mobile phone'], ['música', 'მუსიკა', 'music'], ['festa', 'წვეულება', 'party'], ['som', 'ხმა / ჟღერადობა', 'sound'],
    ['ritmo', 'რიტმი', 'rhythm'], ['palco', 'სცენა', 'stage'], ['concerto', 'კონცერტი', 'concert'], ['público', 'აუდიტორია / საჯარო', 'audience / public'], ['e', 'და', 'and'],
    ['ou', 'ან', 'or'], ['mas', 'მაგრამ', 'but'], ['porque', 'იმიტომ, რომ', 'because'], ['se', 'თუ', 'if'], ['com', 'ერთად (-თან)', 'with'],
    ['sem', 'გარეშე', 'without'], ['para', '-თვის / მიმართულებით', 'for / to'], ['também', 'ასევე', 'also'], ['só', 'მხოლოდ', 'only'], ['mais', 'მეტი', 'more'],
    ['menos', 'ნაკლები', 'less'], ['então', 'მაშინ / ესე იგი', 'so / then'], ['talvez', 'ალბათ', 'maybe'], ['claro', 'რა თქმა უნდა', 'of course'], ['muito', 'ძალიან / ბევრი', 'very / a lot'],
  ],
  en: [
    ['achieve', 'მიღწევა', ''], ['consistent', 'თანმიმდევრული', ''], ['improve', 'გაუმჯობესება', ''], ['recover', 'აღდგენა', ''], ['effort', 'ძალისხმევა', ''],
    ['goal', 'მიზანი', ''], ['habit', 'ჩვევა', ''], ['progress', 'პროგრესი', ''], ['routine', 'რუტინა, დღის რეჟიმი', ''], ['schedule', 'განრიგი', ''],
    ['deadline', 'ბოლო ვადა', ''], ['priority', 'პრიორიტეტი', ''], ['reliable', 'სანდო', ''], ['efficient', 'ეფექტიანი', ''], ['available', 'ხელმისაწვდომი / თავისუფალი', ''],
    ['approach', 'მიდგომა', ''], ['awareness', 'ცნობიერება', ''], ['behaviour', 'ქცევა', ''], ['challenge', 'გამოწვევა', ''], ['confident', 'თავდაჯერებული', ''],
    ['determined', 'შეუპოვარი', ''], ['grateful', 'მადლიერი', ''], ['mindset', 'აზროვნების წესი', ''], ['purpose', 'დანიშნულება, მიზანი', ''], ['patience', 'მოთმინება', ''],
    ['resilient', 'მდგრადი, სწრაფად აღმდგენი', ''], ['humble', 'თავმდაბალი', ''], ['ambitious', 'ამბიციური', ''], ['focus', 'კონცენტრაცია', ''], ['distraction', 'ყურადღების გამფანტველი', ''],
    ['overwhelmed', 'გადატვირთული (ემოციურად)', ''], ['exhausted', 'სრულიად დაქანცული', ''], ['anxious', 'შეშფოთებული', ''], ['relieved', 'შვებით', ''], ['thrilled', 'აღფრთოვანებული', ''],
    ['proud', 'ამაყი', ''], ['honest', 'გულწრფელი', ''], ['genuine', 'ნამდვილი', ''], ['brief', 'მოკლე', ''], ['obvious', 'აშკარა', ''],
    ['subtle', 'დახვეწილი, ძნელად შესამჩნევი', ''], ['vivid', 'ნათელი, ცოცხალი', ''], ['rough', 'უხეში / მიახლოებითი', ''], ['smooth', 'გლუვი / შეუფერხებელი', ''], ['steady', 'სტაბილური', ''],
    ['gradually', 'თანდათან', ''], ['eventually', 'საბოლოოდ', ''], ['actually', 'სინამდვილეში', ''], ['basically', 'არსებითად', ''], ['definitely', 'აუცილებლად', ''],
    ['probably', 'ალბათ', ''], ['rarely', 'იშვიათად', ''], ['frequently', 'ხშირად', ''], ['meanwhile', 'ამასობაში', ''], ['although', 'მიუხედავად იმისა, რომ', ''],
    ['however', 'თუმცა', ''], ['therefore', 'ამიტომ', ''], ['whereas', 'მაშინ როცა', ''], ['unless', 'თუ არა', ''], ['despite', 'მიუხედავად', ''],
    ['afford', 'შეძლება (ფინანსურად)', ''], ['avoid', 'თავის არიდება', ''], ['convince', 'დარწმუნება', ''], ['deserve', 'დამსახურება', ''], ['encourage', 'გამხნევება', ''],
    ['ensure', 'უზრუნველყოფა', ''], ['expand', 'გაფართოება', ''], ['figure out', 'გარკვევა, მიხვედრა', ''], ['give up', 'დანებება', ''], ['keep up', 'ტემპის შენარჩუნება', ''],
    ['look forward to', 'მოუთმენლად ლოდინი', ''], ['make sure', 'დარწმუნება (რომ...)', ''], ['pick up', 'აწევა / სწრაფად ათვისება', ''], ['put off', 'გადადება', ''], ['run out of', 'ამოწურვა', ''],
    ['set up', 'მოწყობა, აწყობა', ''], ['show up', 'გამოჩენა, მოსვლა', ''], ['take care of', 'ზრუნვა', ''], ['turn down', 'უარის თქმა / ხმის დაწევა', ''], ['work out', 'ვარჯიში / მოგვარება', ''],
    ['struggle', 'ბრძოლა, გაჭირვება', ''], ['benefit', 'სარგებელი', ''], ['decline', 'კლება / უარი', ''], ['emerge', 'გამოჩენა', ''], ['enhance', 'გაძლიერება', ''],
    ['estimate', 'შეფასება (მიახლოებით)', ''], ['evaluate', 'შეფასება', ''], ['generate', 'წარმოქმნა', ''], ['implement', 'განხორციელება', ''], ['maintain', 'შენარჩუნება', ''],
    ['obtain', 'მოპოვება', ''], ['pursue', 'მისწრაფება, დევნა (მიზნის)', ''], ['reduce', 'შემცირება', ''], ['require', 'მოთხოვნა, საჭიროება', ''], ['sustain', 'შენარჩუნება ხანგრძლივად', ''],
    ['audience', 'აუდიტორია', ''], ['crowd', 'ბრბო, ხალხი', ''], ['venue', 'ღონისძიების ადგილი', ''], ['gig', 'გამოსვლა (DJ/მუსიკოსის)', ''], ['booking', 'დაჯავშნა / ბუქინგი', ''],
    ['release', 'გამოშვება (ტრეკის)', ''], ['label', 'ლეიბლი', ''], ['track', 'ტრეკი', ''], ['remix', 'რემიქსი', ''], ['royalty', 'ჰონორარი (საავტორო)', ''],
    ['income', 'შემოსავალი', ''], ['expense', 'ხარჯი', ''], ['invoice', 'ინვოისი, ანგარიშ-ფაქტურა', ''], ['contract', 'კონტრაქტი', ''], ['negotiate', 'მოლაპარაკება', ''],
    ['brand', 'ბრენდი', ''], ['reach', 'მიღწევა / წვდომა', ''], ['engagement', 'ჩართულობა', ''], ['feedback', 'უკუკავშირი', ''], ['launch', 'გაშვება', ''],
    ['nutrition', 'კვება', ''], ['protein', 'ცილა', ''], ['portion', 'პორცია', ''], ['craving', 'ძლიერი სურვილი (საჭმლის)', ''], ['hydrated', 'საკმარისად წყალმიღებული', ''],
    ['soreness', 'კუნთის ტკივილი ვარჯიშის შემდეგ', ''], ['injury', 'ტრავმა', ''], ['posture', 'პოზა, ტანის დაჭერა', ''], ['stretch', 'გაჭიმვა', ''], ['endurance', 'გამძლეობა', ''],
    ['strength', 'ძალა', ''], ['breath', 'სუნთქვა (არს.)', ''], ['breathe', 'სუნთქვა (ზმნა)', ''], ['calm', 'მშვიდი', ''], ['peace', 'სიმშვიდე', ''],
    ['wisdom', 'სიბრძნე', ''], ['insight', 'ღრმა გაგება', ''], ['intention', 'განზრახვა', ''], ['gratitude', 'მადლიერება', ''], ['abundance', 'სიუხვე', ''],
    ['fulfilled', 'სრულყოფილი, კმაყოფილი', ''], ['worthwhile', 'ღირებული', ''], ['meaningful', 'აზრიანი', ''], ['inevitable', 'გარდაუვალი', ''], ['reluctant', 'უხალისო', ''],
    ['eager', 'მონდომებული', ''], ['keen on', 'გატაცებული რამით', ''], ['aware of', 'ინფორმირებული', ''], ['capable of', 'შესაძლებელი, უნარიანი', ''], ['responsible for', 'პასუხისმგებელი', ''],
    ['take for granted', 'თავისთავად ცხადად მიღება', ''], ['on the other hand', 'მეორე მხრივ', ''], ['in the long run', 'გრძელვადიან პერსპექტივაში', ''], ['by the way', 'სხვათა შორის', ''], ['as soon as', 'როგორც კი', ''],
    ['so far', 'ჯერჯერობით', ''], ['at least', 'სულ მცირე', ''], ['after all', 'ბოლოს და ბოლოს', ''], ['it depends', 'გააჩნია', ''], ['to be honest', 'გულწრფელად რომ ვთქვა', ''],
    ['it’s worth it', 'ღირს', ''], ['no matter what', 'რაც არ უნდა მოხდეს', ''], ['step by step', 'ნაბიჯ-ნაბიჯ', ''], ['on purpose', 'განზრახ', ''], ['by accident', 'შემთხვევით', ''],
  ],
};
const PHRASES = {
  pt: [['Como te chamas?', 'რა გქვია?'], ['Chamo-me …', 'მე მქვია …'], ['Não percebo.', 'ვერ გავიგე.'], ['Pode repetir, por favor?', 'გაიმეორებთ, თუ შეიძლება?'], ['Fala inglês?', 'ინგლისური იცით?'],
    ['Quanto custa?', 'რა ღირს?'], ['A conta, por favor.', 'ანგარიში, თუ შეიძლება.'], ['Onde fica a casa de banho?', 'სად არის ტუალეტი?'], ['Um café, por favor.', 'ერთი ყავა, თუ შეიძლება.'], ['Estou a aprender português.', 'პორტუგალიურს ვსწავლობ.'],
    ['Vou ao ginásio.', 'სპორტდარბაზში მივდივარ.'], ['Sou DJ e produtor.', 'DJ და პროდიუსერი ვარ.'], ['Tenho fome.', 'მშია.'], ['Tenho sede.', 'მწყურია.'], ['Estou cansado.', 'დაღლილი ვარ.'],
    ['Até amanhã!', 'ხვალამდე!'], ['Que horas são?', 'რომელი საათია?'], ['Posso pagar com cartão?', 'ბარათით გადახდა შეიძლება?'], ['Gosto muito disto.', 'ეს ძალიან მომწონს.'], ['Com calma.', 'მშვიდად, აუჩქარებლად.'],
    ['Tudo bem, obrigado.', 'ყველაფერი კარგადაა, მადლობა.'], ['Desculpe, estou atrasado.', 'ბოდიში, ვაგვიანებ.'], ['Onde é a estação?', 'სად არის სადგური?'], ['Pode ajudar-me?', 'დამეხმარებით?'], ['Muito prazer.', 'სასიამოვნოა.']],
  en: [['It’s not about perfect, it’s about consistent.', 'მთავარი სრულყოფა კი არა, თანმიმდევრულობაა.'], ['I’m looking forward to it.', 'მოუთმენლად ველი.'], ['Let’s get it done.', 'მოდი, გავაკეთოთ.'], ['I’ll keep you posted.', 'საქმის კურსში გამყოფებ.'], ['That makes sense.', 'ლოგიკურია.'],
    ['I couldn’t agree more.', 'სრულიად გეთანხმები.'], ['Could you walk me through it?', 'ნაბიჯ-ნაბიჯ ამიხსნი?'], ['I’m on it.', 'ვაკეთებ, ჩემზეა.'], ['No pressure.', 'არ გაინერვიულო, არ გაძალებ.'], ['It’s up to you.', 'შენზეა დამოკიდებული.'],
    ['Better late than never.', 'გვიან ჯობია, ვიდრე არასდროს.'], ['Small steps every day.', 'პატარა ნაბიჯები ყოველდღე.'], ['I’ll figure it out.', 'მივხვდები, გავარკვევ.'], ['Thanks for having me.', 'მადლობა მოწვევისთვის.'], ['What’s the set time?', 'რა დროს იწყება ჩემი სეტი?'],
    ['Can you send me the rider?', 'რაიდერს გამომიგზავნი?'], ['Let’s touch base next week.', 'მომავალ კვირას დავუკავშირდეთ.'], ['I’m running late.', 'ვაგვიანებ.'], ['Keep it up!', 'ასე გააგრძელე!'], ['Take it easy.', 'ნუ ინერვიულებ / მშვიდად.']],
};
